stages:
  - version
  - build
  - deploy

autoversion:
  stage: version
  script:
    - sh autoversion.sh
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore.*/
  tags:
    - 'sencha2'

build:
  stage: build
  only:
    - merge_requests
    - tags
  script:
    - npm run gitlab
  tags:
    - 'sencha2'

DeployArtifacts:
  stage: deploy
  before_script:
    - sonar-scanner -Dsonar.host.url=http://sonar.gnp.mx:9000 -Dsonar.projectVersion=$CI_COMMIT_TAG
  script:
    - bash automic_deploy_gae.sh
  tags:
    - 'artifactDeployer'
  only:
    - tags
  when: manual