runtime: python37
service: default
handlers:
    - url: /(.*\.(gif|png|jpg|css|js|woff2|ttf|woff|svg)(|\.map))$
      static_files: dist/gae-lab-seguridad/\1
      upload: dist/gae-lab-seguridad/(.*)(|\.map)
    - url: /(.*)
      static_files: dist/gae-lab-seguridad/index.html
      upload: dist/gae-lab-seguridad/index.html
